
server:
  port: 1234

feeUrl:
  bithumb : https://www.bithumb.com/customer_support/info_fee

cache:
  ttl: # time to live
    default: 10000 # 10s
    # default: 1000 # 1s test
    withdrawalFee: 3600000 # 1h